#!/bin/bash

set -e

# source the common build functions
SCRIPT_DIR=$(dirname "$0")
source "${SCRIPT_DIR}/ios_build_functions.sh"

function setup ()
{
    if [ "${ROOT_PATH}/External/libgit2-ios/lib/libgit2-ios.a" -nt "${ROOT_PATH}/External/libgit2" ]
    then
        echo "No update needed."
        exit 0
    fi

    LIBRARY_NAME="libgit2"
    LIB_PATH="${ROOT_PATH}/External/libgit2-ios"
    rm -rf "${LIB_PATH}"

    pushd "${ROOT_PATH}/External/libgit2" > /dev/null
}

function build_libgit2 ()
{
    rm -rf "build"
    mkdir "build"

    mkdir -p "${ROOT_PATH}/External/libgit2-ios/lib"

    pushd "build" > /dev/null

    # LOL Cmake
    if [ "${ARCH}" != "x86_64" ]
    then
        SYS_ROOT="-DCMAKE_OSX_SYSROOT=${SDKROOT}"
    fi

    # install the each built arch somewhere sane
    INSTALL_PREFIX="${ROOT_PATH}/External/libgit2-ios/bin/${PLATFORM}-${ARCH}.sdk"

    # echo "${INSTALL_PREFIX}"

    mkdir -p "${INSTALL_PREFIX}"

    LOG="${INSTALL_PREFIX}/build-libgit2.log"
    echo "$LOG"

    cmake \
        -DCMAKE_C_COMPILER_WORKS:BOOL=ON \
        -DBUILD_SHARED_LIBS:BOOL=OFF \
        -DCMAKE_PREFIX_PATH:PATH="${ROOT_PATH}/External/libssh2-ios/bin/${SDKROOT}-${ARCH}.sdk" \
        -DPKG_CONFIG_USE_CMAKE_PREFIX_PATH:BOOL=ON \
        -DCMAKE_INSTALL_PREFIX:PATH="${INSTALL_PREFIX}/" \
        -DBUILD_CLAR:BOOL=OFF \
        -DTHREADSAFE:BOOL=ON \
        -DCURL:BOOL=OFF \
        -DCMAKE_C_FLAGS:STRING="-fembed-bitcode" \
        "${SYS_ROOT}" \
        -DCMAKE_OSX_ARCHITECTURES:STRING="${ARCH}" \
        .. >> "${LOG}" 2>&1
    cmake --build . --target install >> "${LOG}" 2>&1

    # push the built library into the list
    BUILT_LIB_PATHS+=("${INSTALL_PREFIX}/lib/libgit2.a")
    popd > /dev/null
}

function fat_binary ()
{
    echo "Building fat binary..."

    mkdir -p "${ROOT_PATH}/External/libgit2-ios/lib/simulator"
    mkdir -p "${ROOT_PATH}/External/libgit2-ios/lib/device"

    SIMULATOR_LIBS=()
    DEVICE_LIBS=()
    SIMULATOR_LIBS+=("${ROOT_PATH}/External/libgit2-ios/bin/iphonesimulator-x86_64.sdk/lib/libgit2.a")
    SIMULATOR_LIBS+=("${ROOT_PATH}/External/libgit2-ios/bin/iphonesimulator-arm64.sdk/lib/libgit2.a")

    DEVICE_LIBS+=("${ROOT_PATH}/External/libgit2-ios/bin/iphoneos-arm64.sdk/lib/libgit2.a")

    # 创建模拟器的 fat binary
    if [ ${#SIMULATOR_LIBS[@]} -gt 0 ]; then
        echo "Creating simulator binaries..."
        lipo -create ${SIMULATOR_LIBS[@]} -output "${ROOT_PATH}/External/libgit2-ios/lib/simulator/libgit2.a"
    fi

    if [ ${#DEVICE_LIBS[@]} -gt 0 ]; then
        echo "Creating simulator binaries..."
        lipo -create ${DEVICE_LIBS[@]} -output "${ROOT_PATH}/External/libgit2-ios/lib/device/libgit2.a"
    fi

    ln -sf simulator/libgit2.a "${ROOT_PATH}/External/libgit2-ios/libgit2-ios.a"
    
    echo "Build results:"
    echo "Simulator libraries: ${ROOT_PATH}/External/libgit2-ios/lib/simulator/"
    echo "Device libraries: ${ROOT_PATH}/External/libgit2-ios/lib/device/"
    
    # 验证构建的库
    echo "Verifying architectures in built libraries:"
    echo "Simulator libgit:"
    lipo -info "${ROOT_PATH}/External/libgit2-ios/lib/simulator/libgit2.a"
    echo "Device libgit2:"
    lipo -info "${ROOT_PATH}/External/libgit2-ios/lib/device/libgit2.a"

    echo "Building done."
}

build_all_archs setup build_libgit2 fat_binary
